#if !defined N_CARPARTS_INCLUDED
	#define N_CARPARTS_INCLUDED
#else
	#endinput
#endif

/*
Hydraulic
*/
#define Hydraulics 1087

/*
Spoilers
*/
#define Spoiler_Pro 1000 
#define Spoiler_Win 1001
#define Spoiler_Drag 1002
#define Spoiler_Alpha 1003
#define Spoiler_Champ 1014
#define Spoiler_Race 1015
#define Spoiler_Worx 1016
#define Spoiler_Fury 1023

/*
Hoods
*/
#define Hood_Champ 1004
#define Hood_Fury 1005
#define Hood_Race 1011
#define Hood_Worx 1012

/*
Nitro / NOS
*/
#define Nitro_5times 1008
#define Nitro_2times 1009
#define Nitro_10times 1010

/*
Lamps
*/
#define Lamps_Round 1013
#define Lamps_Square 1024

/*
Skirts
*/
#define Sideskirt_Right 1007
#define Sideskirt_Left 1017

/*
exhaust
*/
#define Exhaust_Upswept 1018
#define Exhaust_Twin 1019
#define Exhaust_Large 1020
#define Exhaust_Medium 1021
#define Exhaust_Small 1022

/*
Wheels
*/
#define Wheels_Offroad 1025
#define Wheels_Shadow 1073
#define Wheels_Mega 1074
#define Wheels_Rimshine 1075
#define Wheels_Wires 1076
#define Wheels_Classic 1077
#define Wheels_Twist 1078
#define Wheels_Cutter 1079
#define Wheels_Switch 1080
#define Wheels_Grove 1081
#define Wheels_Import 1082
#define Wheels_Dollar 1083
#define Wheels_Trance 1084
#define Wheels_Atomic 1085
#define Wheels_Ahab 1096
#define Wheels_Virtual 1097
#define Wheels_Access 1098

/*
Vents
*/
#define Vents_Left_Oval 1142
#define Vents_Right_Oval 1143
#define Vents_Left_Square 1144
#define Vents_Right_Square 1145