#if !defined N_COLORS_INCLUDED
	#define N_COLORS_INCLUDED
#else
	#endinput
#endif

/*
Couleurs au format RGBA
*/
#define C_WHITE 0xFFFFFFFF
#define C_BLACK 0x000000FF
#define C_GREY 0x0000007F
#define C_RED 0xFF0000C3
#define C_BLUE 0x0000FFAA
#define C_YELLOW 0xFFCE0092
#define C_ORANGE 0xE67A00FF

/*
Embeded Colors
*/
#define CE_PURPPLE "{8C3C63}"
#define CE_WHITE "{FFFFFF}"
#define CE_GREY "{666666}"
#define CE_BLACK "{000000}"
