#if !defined N_MAIN_INCLUDED
	#define N_MAIN_INCLUDED
#else
	#error La bibliotheque NyanRP ne dois être incluse qu une seul fois !
#endif

/*
YSI
*/
#include <YSI\y_stringhash>
#include <YSI\y_users>
#include <YSI\y_uvar>
#include <YSI\y_commands>

/*
Nyan-RP
*/
#include <nyanrp\n_colors>
#include <nyanrp\n_users>
#include <nyanrp\n_strings>
#include <nyanrp\n_pos>
#include <nyanrp\n_chat>
#include <nyanrp\n_admins>
#include <nyanrp\n_vehicles>
