#if !defined N_MAIN_INCLUDED
	#define N_MAIN_INCLUDED
#else
	#error La bibliotheque NyanRP ne dois être incluse qu une seul fois !
#endif

//-------------[SAMP]--------------
#include ".\SAMP\a_samp.inc"

//------------[Tweaks]-------------
#include ".\NYANRP\n_tweaks.inc"

//-------------[YSI]---------------
#include ".\YSI\y_main"

//----[Fast Dialog Processor]------
#include ".\fdialog.inc"

//-----------[DJSon]---------------
#include ".\djson"

//----------[Nyan-RP]--------------
#include ".\NYANRP\n_colors"
#include ".\NYANRP\n_users"
#include ".\NYANRP\n_dialogs"
#include ".\NYANRP\n_strings"
#include ".\NYANRP\n_pos"
#include ".\NYANRP\n_chat"
#include ".\NYANRP\n_admins"
#include ".\NYANRP\n_vehicles"
#include ".\NYANRP\n_cmds"


